name: CD

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build production API image
        run: docker build -t zabki-location-api:latest .
